# Generated by Django 2.1.7 on 2019-05-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=50)),
                ('info', models.TextField()),
            ],
        ),
    ]
